name: GitHub Backup to Drive

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:  # Manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq rclone

      - name: Run backup script
        run: |
          chmod +x github_backup.sh
          GITHUB_TOKEN=${{ secrets.PERSONAL_GITHUB_TOKEN }} ./github_backup.sh

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONFIG }}" > ~/.config/rclone/rclone.conf

      - name: Upload to Google Drive
        run: |
          LATEST_BACKUP=$(ls -td backups/backup_* | head -1)
          if [ -n "$LATEST_BACKUP" ]; then
            # Permanently delete all contents in the target Google Drive folder without sending to trash
            rclone delete gdrivegit:GitHub_Backups/ --drive-use-trash=false || echo "Folder may not exist or already empty, skipping delete."
            rclone copy "$LATEST_BACKUP" gdrivegit:GitHub_Backups/ --progress
          else
            echo "No backup found to upload"
          fi
